// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Axios = require("axios");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");

function url(region) {
  return "https://api.openbrewerydb.org/breweries?by_state=" + $$String.lowercase(region).replace((/\s/g), "_");
}

function BreweryList(Props) {
  var region = Props.region;
  var match = React.useState((function () {
          return /* [] */0;
        }));
  var setBreweries = match[1];
  React.useEffect((function () {
          console.log("running effect", region);
          Axios.get(url(region)).then((function (response) {
                    return Promise.resolve(Curry._1(setBreweries, response.data));
                  })).catch((function (error) {
                  return Promise.resolve((console.log(error), /* () */0));
                }));
          return undefined;
        }), /* array */[region]);
  return React.createElement("div", undefined);
}

var make = BreweryList;

exports.url = url;
exports.make = make;
/* axios Not a pure module */
